### ISSUE TITLE
Getting no completion

### ISSUE THREAD

**Issue by doggo-rules** [dansomething/coc-groovy#10]
I just installed Groovy with pacman (version 3.0.7) and installed coc-groovy. I start trying `println` but get no completion. When I trigger completion with nothing typed, I only see `run` and `main`. The extension says language server started when I open Neovim. Running my script with `groovy foo.groovy` is fine.

**Comment by dansomething** [comment]
Out of the box you will only get completion for definitions in the open Groovy file or other Groovy source files in the same directory tree.  Try typing in a core class name like, `System.` or `String.`, and then trigger completion and you should get some options. If you want additional completion sources you'll need to add them in the settings via [groovy.project.referencedLibraries](https://github.com/dansomething/coc-groovy#supported-settings).

For example:
```json
{
  "groovy.project.referencedLibraries": [
    "/path/to/jars/some.jar"
  ]
}
```

Also, I'm not sure you'll get completion for standalone keywords like `println`.

**Comment by doggo-rules** [comment]
Ah ok, closing this issue

**Comment by dansomething** [comment]
Note, if you have a Maven project the classpath will be picked up and the dependency libraries will be automatically added for you. Gradle support is still a work in progress. See #12
