### ISSUE TITLE
Broken pipe Error

### ISSUE THREAD

**Issue by ray0x44** [dansomething/coc-groovy#19]
Command 
```
~/.config/coc/extensions/node_modules/coc-groovy/utils/gradle-classpath/bin/gradle-classpath --path-separator=: --output-file=~/.config/coc/extensions/coc-groovy-data/groovy_ws_c3dcb2b17f4244c8ba399bf909779121/.groovy-classpath --regenerate-file=false
```
execute failed with response: `Error! Broken pipe`, which cause the extension start failed. How should i slove it?
Java version 11
Gradle wrapper 7.1

**Comment by dansomething** [comment]
What error do you get when you run this command directly?
```
~/.config/coc/extensions/node_modules/coc-groovy/utils/gradle-classpath/bin/gradle-classpath --path-separator=: --output-file=~/.config/coc/extensions/coc-groovy-data/groovy_ws_c3dcb2b17f4244c8ba399bf909779121/.groovy-classpath --regenerate-file=false
```

Do you have a simple example project on which this error can be reproduced?

**Comment by ray0x44** [comment]
> What error do you get when you run this command directly?
> 
> ```
> ~/.config/coc/extensions/node_modules/coc-groovy/utils/gradle-classpath/bin/gradle-classpath --path-separator=: --output-file=~/.config/coc/extensions/coc-groovy-data/groovy_ws_c3dcb2b17f4244c8ba399bf909779121/.groovy-classpath --regenerate-file=false
> ```
> 
> Do you have a simple example project on which this error can be reproduced?

The same output: `Error! Broken pipe`

And i got the same output if i run:
```
java -classpath ~/.config/coc/extensions/node_modules/coc-groovy/utils/gradle-classpath/lib/gradle-classpath-1.1.1.jar:~/.config/coc/extensions/node_modules/coc-groovy/utils/gradle-classpath/lib/gradle-tooling-api-7.0.jar:~/.config/coc/extensions/node_modules/coc-groovy/utils/gradle-classpath/lib/picocli-4.6.1.jar:~/.config/coc/extensions/node_modules/coc-groovy/utils/gradle-classpath/lib/slf4j-simple-1.7.30.jar:~/.config/coc/extensions/node_modules/coc-groovy/utils/gradle-classpath/lib/slf4j-api-1.7.30.jar com.dansomething.gradle.classpath.App --path-separator=: --output-file=~/.config/coc/extensions/coc-groovy-data/groovy_ws_c3dcb2b17f4244c8ba399bf909779121/.groovy-classpath --regenerate-file=false
```
which is what gradle-classpath eventually execute, i try upgrade `gradle-tooling-api-7.0.jar` to `gradle-tooling-api-7.1.jar` and seems no help.
But from java class loading log, i found the error seems to hava some connection with the socket connection with gradle daemon, so i killed all GradleDaemon and re-run the java command, it works ok now and output:
```
Wrote classpath file '~/.config/coc/extensions/coc-groovy-data/groovy_ws_c3dcb2b17f4244c8ba399bf909779121/.groovy-classpath'
BUILD SUCCESS
```
may be the error is caused by my `coc-metals` or `coc-java` extension  on gradle daemon i'm not sure, i need more tests.

**Comment by dansomething** [comment]
That is odd. I'm glad you got it figured out for now. Maybe at some point I can find a way to improve the error output to help future troubleshooting.

**Comment by dansomething** [comment]
See dansomething/gradle-classpath/issues/1
