### ISSUE TITLE
languageserver.groovy timeout after 5000ms.

### ISSUE THREAD

**Issue by rohitbishnoi** [dansomething/coc-groovy#2]
![Screenshot 2020-05-04 at 10 47 38 AM](https://user-images.githubusercontent.com/6151462/80937955-cf704700-8df4-11ea-92e8-469c25aa2470.png)

**Comment by dansomething** [comment]
Based off the provided information, its difficult to say what is happening. You'll need to confirm the Groovy language server is running properly and there are no errors.

1) In Vim you can run the `:messages` command to look for "Groovy Language Server" messages or related errors. If its working properly you should see:
```
[coc.nvim] Groovy Language Server starting...
[coc.nvim] Groovy Language Server started!
```
2) You can also check the Groovy language server logs.
    1) Enable the Groovy language server logging in your [coc.nvim config](https://github.com/neoclide/coc.nvim/wiki/Using-the-configuration-file).
        * `"groovy.trace.server": "verbose"`
        *  Then restart Vim or run `:CocRestart`
    2) If the server is running and the trace logging is properly configured then log entries will be created. You may view them by running the [coc.nvim command](https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel) to show them.
        * `:CocCommand workspace.showOutput groovy`
        * Look for errors and make sure requests and responses are being logged as you make code changes.
3) If it all appears to be loading and working with no error messages then it could be simply taking a long time on your system. If that is the case then can you can try increasing the `suggest.timeout` in your [coc.nvim config](https://github.com/neoclide/coc.nvim/wiki/Using-the-configuration-file). It defaults to `5000` milliseconds. This example increases it by 3 seconds.
    1) `"suggest.timeout": 8000`
