### ISSUE TITLE
Groovy Language Server classpath command failed

### ISSUE THREAD

**Issue by leorr** [dansomething/coc-groovy#23]
I've been getting this error opening a .groovy file, those files like gradle-calsspath and groovy_ws_ are not present in theit paths any ideia on how to solve this?
`[coc.nvim] Groovy Language Server classpath command failed "cd /home/leorr/moskit-back && /home
/leorr/.config/coc/extensions/node_modules/coc-groovy/utils/gradle-classpath/bin/gradle-classpa
th --path-separator=: --output-file=/home/leorr/.config/coc/extensions/coc-groovy-data/groovy_w
s_6c9c93286599772df54e8eb19d084f32/.groovy-classpath --regenerate-file=false"`

**Comment by dansomething** [comment]
I would start by taking a look at this thread: https://github.com/dansomething/coc-groovy/issues/19#issuecomment-879439733
