### ISSUE TITLE
Unsupported class file major version

### ISSUE THREAD

**Issue by martinlauer** [dansomething/coc-groovy#31]
Hi,
I'm using openjdk@18 on aarch64 (Apple M1).

`~/.config/coc/extensions/node_modules/coc-groovy/utils/gradle-classpath/bin/gradle-classpath
Error! startup failed:
General error during conversion: Unsupported class file major version 62`

I strongly assume this is related to the used gradle version 7.0 that [only supports Java Version 16](https://docs.gradle.org/current/userguide/compatibility.html). Java 16 isn't available for M1, so this is a showstopper for me.

**Comment by dansomething** [comment]
Thanks, I'll take a look when I can find some time.

**Comment by dansomething** [comment]
This should be fixed In the latest release adding support for Java 17 and 18.

https://github.com/dansomething/coc-groovy/releases/tag/v1.2.0
