### ISSUE TITLE
No code completion for gradle

### ISSUE THREAD

**Issue by Taz03** [dansomething/coc-groovy#34]
rn i don't get any code completion for gradle files
![image](https://user-images.githubusercontent.com/73871477/218570417-eac3d626-ddb9-42f2-9d23-beb96fce5860.png)

also for some reason when i open a bracket it is misaligned
![image](https://user-images.githubusercontent.com/73871477/218570682-9843cdc0-37c3-4aa8-907e-c49d63be9078.png)

**Comment by dansomething** [comment]
I'm not sure if the groovy language server will support completion in Gradle files. I'll have to look into that. As for the formatting that's probably a local issue. The Groovy language server supports the following features for Groovy files:

- completion
- definition
- documentSymbol
- hover
- references
- rename
- signatureHelp
- symbol
- typeDefinition

**Comment by Taz03** [comment]
@dansomething is there any other plugins u know to make my experience better in gradle?

**Comment by dansomething** [comment]
Sorry, I'm not aware of a plugin that does this in vim, but that doesn't mean there isn't one out there.

**Comment by Taz03** [comment]
well i searched for it and can't find any, there is none i believe
