### ISSUE TITLE
JAVA_HOME does not point to a JDK

### ISSUE THREAD

**Issue by Afollet** [dansomething/coc-groovy#36]
Hey,

I'm on Ubuntu linux. My java home is set in my .bashrc like `export JAVA_HOME="/usr/lib/jvm/java-11-openjdk-amd64"`

However, whenever I open a groovy file the pop up says "The JAVA_HOME environment variable does not point to a JDK". The rest of the message is cut off by the length of the pop up box. 

From there, if I select either yes or no it doesn't seem to do anything.

Am I doing something wrong here?

**Comment by dansomething** [comment]
I'll need more debug info. I'll see if I can replicate the problem. In the mean time maybe you can provide more from the logs?

As far as debugging goes:
1) What's the output of running `:messages` in vim?
1) Take a look at the logs available from `:CocCommand workspace.showOutput`
    1) You might need to enable trace logs in your `CocConfig`.  `"groovy.trace.server": "verbose"`

Let me know if you capture any more useful logs or other information to help troubleshoot.

**Comment by dansomething** [comment]
Do you have an example project to demonstrate the error?

**Comment by Afollet** [comment]
Thanks for being patient with me, I resolved it by adding "groovy.java.home" explicitly to my coc-settings:

```
{
    "groovy.java.home": "/usr/lib/jvm/java-8-openjdk-amd64"
}
```

As well, it seems to be looking in some directories which are not relevant to the project. Is there a way I can control this behavior?

Thanks for making this project, mate. Intellij is insufferable for the project I'm working on.

**Comment by dansomething** [comment]
It's odd that it didn't pick up your JAVA_HOME. It is configured to [look for it](https://github.com/dansomething/coc-groovy/blob/master/src/requirements.ts#L50). I'd have to see a stack trace and/or other logs to figure it out, but it sounds like you'll be using the workaround for now.

> it seems to be looking in some directories which are not relevant to the project. Is there a way I can control this behavior?

This is currently a limitation of the [Groovy Language Server](https://github.com/GroovyLanguageServer/groovy-language-server/blob/master/src/main/java/net/prominic/groovyls/config/CompilationUnitFactory.java#L160). It scans for all `.groovy` files in each directory under the workspace root. The workspace root is determined by the location of the main project file ( pom.xml, build.gradle, etc.) or the currently load groovy file.

**Comment by Afollet** [comment]
>I'd have to see a stack trace and/or other logs to figure it out, but it sounds like you'll be using the workaround for now.
     There was nothing logged in `:messages` and `:CocCommand workspace.showOutput`. It leads me to suspect it might by a system issue. 
     
I'm testing out the rest of the functionality, like:  
* Find References
* Go to Definition
* Refactor Rename

The code completion and hover works beautifully though.
