### ISSUE TITLE
Is it possible to add a way to fix missing imports?

### ISSUE THREAD

**Issue by jonathan-elize** [dansomething/coc-groovy#39]
This isn't a bug but a feature request. Is there anyway to incorporate a way to add missing imports to a file?

**Comment by dansomething** [comment]
This project is a thin wrapper around the [Groovy Language Server](https://github.com/GroovyLanguageServer/groovy-language-server). If an "organize imports" feature was added there it should be relatively easy to add support here.

**Comment by jonathan-elize** [comment]
Ah ok. Thanks for the explanation! I'll close this issue then as it's not there right now
