### ISSUE TITLE
Set custom formatter

### ISSUE THREAD

**Issue by mosheavni** [dansomething/coc-groovy#5]
Hi, thanks for this plugin!
Is there any way I can configure my own formatter that will be invoked with `<Plug>(coc-format)`?
Thanks.

**Comment by dansomething** [comment]
This plugin is a thin wrapper for the [Groovy Language Server](https://github.com/prominic/groovy-language-server). I think ideally code formatting support would need to be added to it. In the mean time you could invoke another tool from Vim using a customized key mapping. Unfortunately, there doesn't seem to be many options available. [NPM Groovy Lint](https://github.com/nvuillam/npm-groovy-lint) seems like the best choice, but I have not tried it. This [Stackoverflow question](https://stackoverflow.com/questions/130494/is-there-a-source-code-formatter-for-groovy) mentions some other options.

**Comment by mosheavni** [comment]
@dansomething  can I have an option to define my custom formatter?
CoC maintainer says the language server is the one responsible for formatting the code, and I'd like a way to define a formatter as a vim function, can this be achieved?
Thanks.

**Comment by dansomething** [comment]
I agree the language server should be responsible for formatting the code. That is why I think it belongs in the [Groovy Language Server](https://github.com/prominic/groovy-language-server) project and not this thin wrapper around that project. Then it would also benefit anybody using the language server and not just those using coc.nvim. It sounds like what you need is something like [vim-autoformat](https://github.com/Chiel92/vim-autoformat).

**Comment by mosheavni** [comment]
I ended up with this:
```
nmap <expr> <leader>p CocHasProvider('format') ? "\<Plug>(coc-format)" : ":call FormatEqual()\<cr>"
```
Didn't like `vim-autoformat`...
![image](https://user-images.githubusercontent.com/17252601/98268042-ba879280-1f94-11eb-9f98-9b3cba6bd0d6.png)

**Comment by dansomething** [comment]
For now, other formatting alternatives can be gleaned from [Stackoverflow](https://stackoverflow.com/questions/130494/is-there-a-source-code-formatter-for-groovy).
