### ISSUE TITLE
Does support gradle or not ?

### ISSUE THREAD

**Issue by srillia** [dansomething/coc-groovy#8]
support gradle ?

**Comment by dansomething** [comment]
Currently there is no Gradle support. You will need to set `groovy.project.referencedLibraries`.

**Comment by srillia** [comment]
installation takes a long time?,in the end failed,can improved?

**Comment by dansomething** [comment]
In order for me to be able to help I would need a lot more information to understand the issue.

Here are some things that would help, but providing as much information as possible would make troubleshooting easier for you and for me.

* The details of your development environment 
  * For example, Vim or Neovim Version, OS Version, Java Version, Groovy Version or anything relevant to your project or network connection such as using a proxy.
  * The output of `:CocInfo`
  * The output of `:messages`
* Is coc.nvim up to date?
* Are you coc.nvim extensions up to date?
* The steps used to reproduce the problem you are seeing.
* The output of some of the logs from your machine
  * For example, the groovy language server trace, coc.nvim, vim or anything else with relevant output for troubleshooting.
* Is there a sample Groovy project which can used to reproduce the problem?
* Are you able to reproduce the problem use a minimal vim/neovim config?
* Is there any thing else you can add that would help?

**Comment by dansomething** [comment]
Gradle projects are supported now. See https://github.com/dansomething/coc-groovy/pull/12
