### ISSUE TITLE
How do you get auto formatting?

### ISSUE THREAD

**Issue by aotarola** [dansomething/coc-groovy#9]
it seems to be not included in the [features of `coc-groovy`](https://github.com/dansomething/coc-groovy#features). So I was wondering what would be the best way to set up _auto formatting_ on save?

**Comment by dansomething** [comment]
Currently, issue #5 has best information available on handling code formatting. Basically you'll need to [call your own formatter](https://github.com/dansomething/coc-groovy/issues/5#issuecomment-722486911).
